export default {
  codename: '(GitHub) HyperTech99 | Debugging BattleCruiser',
  presentation: '열정적으로 배우는 신입 개발자 지망생입니다.<br/>보기 좋은 음식이 먹기도 좋은 법인 것처럼, 상세한 명세와 문서, 명료한 주석, 클린 코딩을 지향합니다.<br/>“1일 1개발”, “구글링의 생활화”, “StackOverFlow에 답이 있다”를 인생의 모토로 삼고 있습니다.',
  activities: [
    {
      id: 1,
      content: '저현자율형공립고등학교 졸업',
      timestamp: '2018. 02.',
    },
    {
      id: 2,
      content: '세종대학교 컴퓨터공학과 입학',
      timestamp: '2018. 03.',
    },
    {
      id: 3,
      content: '세종대학교 2018 알고리즘 경진대회 장려상 수상',
      timestamp: '2018. 09.',
    },
    {
      id: 4,
      content: '세종대학교 웹개발 동아리 OpenYearRound 7기',
      timestamp: '2019. 04.',
    },
    {
      id: 5,
      content: '세종대학교 2019 알고리즘 경진대회 3등상 수상',
      timestamp: '2019. 09.',
    },
    {
      id: 6,
      content: '세종대학교 제 7회 SW. 인공지능 해커톤 은상 수상',
      timestamp: '2019. 12.',
    },
    {
      id: 7,
      content: 'PiLab 스타트업 병역특례(보충역) 입사',
      timestamp: '2020. 01.',
    },
    {
      id: 8,
      content: '세종대학교 컴퓨터공학과 2학년 수료 (휴학)',
      timestamp: '2020. 02.',
    },
    {
      id: 9,
      content: '병역특례개발자(보충역 산업기능요원) 편입',
      timestamp: '2020. 03.',
    },
  ],
  skillCategory: [
    'General', 'Backend', 'Infra', 'Language', 'Frontend', 'Etc.',
  ],
  skills: [
    {
      id: 1,
      name: 'Linux (Debian)',
      category: 'General',
      image: 'debian.png',
    },
    {
      id: 2,
      name: 'Linux (Ubuntu)',
      category: 'General',
      image: 'ubuntu.png',
    },
    {
      id: 3,
      name: 'Bash Shell',
      category: 'General',
      image: 'shell.png',
    },
    {
      id: 4,
      name: 'Git',
      category: 'General',
      image: 'git.png',
    },
    {
      id: 5,
      name: 'Gradle',
      category: 'General',
      image: 'gradle.jpg',
    },
    {
      id: 6,
      name: 'Node.js',
      category: 'Backend',
      image: 'nodejs.png',
    },
    {
      id: 7,
      name: 'Express',
      category: 'Backend',
      image: 'expressjs.png',
    },
    {
      id: 8,
      name: 'Java Spring',
      category: 'Backend',
      image: 'spring.png',
    },
    {
      id: 9,
      name: 'Spring Boot',
      category: 'Backend',
      image: 'springboot.png',
    },
    {
      id: 10,
      name: 'JUnit',
      category: 'Backend',
      image: 'junit.jpg',
    },
    {
      id: 11,
      name: 'MySQL',
      category: 'Backend',
      image: 'mysql.png',
    },
    {
      id: 12,
      name: 'AWS',
      category: 'Infra',
      image: 'aws.png',
    },
    {
      id: 13,
      name: 'Docker',
      category: 'Infra',
      image: 'docker.jpg',
    },
    {
      id: 14,
      name: 'Kubernetes',
      category: 'Infra',
      image: 'kubernetes.png',
    },
    {
      id: 15,
      name: 'Jenkins',
      category: 'Infra',
      image: 'jenkins.png',
    },
    {
      id: 16,
      name: 'C',
      category: 'Language',
      image: 'c.png',
    },
    {
      id: 17,
      name: 'C++',
      category: 'Language',
      image: 'cpp.jpg',
    },
    {
      id: 18,
      name: 'JAVA',
      category: 'Language',
      image: 'java.png',
    },
    {
      id: 19,
      name: 'Python 3',
      category: 'Language',
      image: 'python.png',
    },
    {
      id: 20,
      name: 'JavaScript/TypeScript',
      category: 'Language',
      image: 'javascript.png',
    },
    {
      id: 21,
      name: 'SQL',
      category: 'Language',
      image: 'sql.png',
    },
    {
      id: 22,
      name: 'Arduino',
      category: 'Language',
      image: 'arduino.jpg',
    },
    {
      id: 23,
      name: 'HTML5',
      category: 'Frontend',
      image: 'html5.png',
    },
    {
      id: 24,
      name: 'CSS3/SASS/SCSS',
      category: 'Frontend',
      image: 'css3.png',
    },
    {
      id: 25,
      name: 'JavaScript (ES5/6/7/TS)',
      category: 'Frontend',
      image: 'javascript.png',
    },
    {
      id: 26,
      name: 'JQuery',
      category: 'Frontend',
      image: 'jquery.gif',
    },
    {
      id: 27,
      name: 'Vue.js',
      category: 'Frontend',
      image: 'vuejs.png',
    },
    {
      id: 28,
      name: 'React.js',
      category: 'Frontend',
      image: 'reactjs.png',
    },
    {
      id: 29,
      name: 'Android Development',
      category: 'Etc.',
      image: 'android.png',
    },
    {
      id: 30,
      name: 'PhotoShop',
      category: 'Etc.',
      image: 'photoshop.jpg',
    },
    {
      id: 31,
      name: 'OA (Word, PPT, Excel)',
      category: 'Etc.',
      image: 'msoffice.png',
    },
  ],
  projectCategory: ['Web', 'Android', 'Etc.'],
  projects: [
    {
      id: 1,
      category: 'Web',
      name: 'SCP Schools',
      link: '',
      screenshot: [],
      discription: 'TCP School을 모방하여 만든 웹 페이지로써, 세종대학교 컴퓨터공학과 1학년 과정에서 배우는 내용들을 정리한 웹 페이지입니다.<br/>이 프로젝트를 진행하면서 HTML, CSS, Javascript에 익숙해졌습니다.',
      stackTags: ['HTML5', 'CSS3', 'Javascript', 'JQuery'],
      content: ' # 테스트합니다.',
    },
    {
      id: 2,
      category: 'Web',
      name: 'My Journal Express',
      link: '',
      screenshot: [],
      discription: '동아리에서 3인 프로젝트 (기획/디자인/개발 중 제가 개발을 담당하였습니다.) 로 진행한 자신만의 저널을 만들 수 있는 웹 서비스로써, 이미지나 동영상, 텍스트를 화면상에 자유롭게 배치가 가능한 것이 특징입니다.<br/>이 프로젝트를 진행하며 REST API 및 Ajax 기술에 대해 상당 부분 이해할 수 있었습니다.',
      stackTags: ['HTML5', 'CSS3', 'Javascript', 'JQuery', 'Node.js', 'EJS', 'Express.js', 'MySQL', 'Docker'],
      content: '',
    },
    {
      id: 3,
      category: 'Web',
      name: 'DK-Zone',
      link: '',
      screenshot: [],
      discription: '페이스북 형태의 SNS 웹 서비스로써, 처음으로 SPA 프레임워크와 UI 프레임워크를 사용하여 만들어 본 프로젝트입니다.<br/>이 프로젝트를 진행하면서, SPA Framework, Client-Side Rendering, Templete, View Component, SPA-router, 반응형 레이아웃 기술 및 기법에 대해 상당 부분 이해할 수 있었습니다.',
      stackTags: ['HTML5', 'CSS3', 'Javascript', 'Vue.js', 'Node.js', 'Express.js', 'MySQL', 'Docker'],
      content: '',
    },
    {
      id: 4,
      category: 'Web',
      name: `HyperTech99's Portpolio`,
      link: '',
      screenshot: [],
      discription: '제 예전 포트폴리오 웹 페이지입니다.<br/>이 프로젝트를 진행하면서, Vue.js보다 좀 더 대중적인 React.js를 사용할 줄 알게 되었습니다. 포트폴리오이기에, 정적인 내용만을 보여준다고 생각하여 백엔드는 구현하지 않고 하드코딩을 통해 구현했었습니다.',
      stackTags: ['HTML5', 'CSS3', 'Javascript', 'React.js'],
      content: '',
    },
    {
      id: 5,
      category: 'Web',
      name: `Sejong HackerTon`,
      link: '',
      screenshot: [],
      discription: '세종대학교 해커톤에서 4인 프로젝트로 진행한 AI 시각화 웹 페이지입니다.<br/>이 프로젝트를 진행하면서, Vue.js, Node.js, Express, MySQL에 완벽하게 숙달될 수 있었습니다. 덤으로, 서버 간 통신[임베디드 장치(Arduino) <-> AI Server(Python) <-> Web Backend(Node.js Express) <-> Web Frontend(Vue.js)]을 구현해 볼 수 있는 좋은 기회였습니다.',
      stackTags: ['HTML5', 'CSS3', 'Javascript', 'Vue.js', 'Node.js', 'Express', 'MySQL'],
      content: '',
    },
    {
      id: 6,
      category: 'Web',
      name: `HyperTech99's Page (The New Portpolio)`,
      link: '',
      screenshot: [],
      discription: '제 현재 포트폴리오 웹 페이지입니다.<br/>하드코딩 특성상 내용 변경 및 유지보수에 불편함을 겪어 이 프로젝트를 진행하게 되었습니다. 이 프로젝트를 진행하면서, Spring Framework를 사용하여 API 백엔드를 구현하여 조금 더 편하게 포트폴리오를 관리할 수 있게 되었습니다.',
      stackTags: ['HTML5', 'CSS3', 'Javascript', 'Vue.js', 'JAVA Spring', 'Mybatis', 'MySQL', 'Docker'],
      content: '',
    },
    {
      id: 7,
      category: 'Web',
      name: `HyperTech99's Archive`,
      link: '',
      screenshot: [],
      discription: 'DevoThink라는 프로그램의 기능에 영감을 받아 만든 온라인 아카이빙 웹 서비스입니다.<br/>이 프로젝트를 진행하면서, Spring Framework에 익숙해지고, Spring Boot, Mybatis를 사용하는 방법을 깨닫게 되었습니다. Node.js를 이용한 단순한 API 서버 대신, Server-Side에서 MVC 모두를 다루어 보는 경험을 할 수 있었습니다. 조금 고전적인 기술이기는 하지만, Server Side Rendering과 Client Side Rendering의 장단점을 파악할 수 있는 기회가 되었습니다.',
      stackTags: ['HTML5', 'CSS3', 'Javascript', 'Vue.js', 'Server-Side Rendering', 'JAVA Spring', 'Spring Boot', 'Mybatis', 'MySQL', 'Docker'],
      content: '',
    },
    {
      id: 8,
      category: 'Web',
      name: `HyperTech99's Storage`,
      link: '',
      screenshot: [],
      discription: '서버의 파일들을 관리할 수 있는 웹 파일 탐색기 프로젝트입니다.<br/>이 프로젝트를 진행하면서, Spring Framework에 매우 숙달되고, 덤으로 JSP를 사용하는 방법을 알 수 있었습니다.',
      stackTags: ['HTML5', 'CSS3', 'JSP', 'JAVA Spring', 'Mybatis', 'MySQL', 'Docker'],
      content: '',
    },
    {
      id: 9,
      category: 'Android',
      name: 'JH-High App',
      link: '',
      screenshot: [],
      discription: '',
      stackTags: ['Android', 'Native Android App'],
      content: '',
    },
    {
      id: 10,
      category: 'Android',
      name: 'My Journal Express Mobile',
      link: '',
      screenshot: [],
      discription: '',
      stackTags: ['Android', 'Web App Sync'],
      content: '',
    },
    {
      id: 11,
      category: 'Android',
      name: 'DK-Zone Mobile',
      link: '',
      screenshot: [],
      discription: '',
      stackTags: ['Android', 'Web App Sync'],
      content: '',
    },
    {
      id: 12,
      category: 'Android',
      name: 'Vega Conflict Central',
      link: '',
      screenshot: [],
      discription: '',
      stackTags: ['Android', 'Native Android App'],
      content: '',
    },
    {
      id: 13,
      category: 'Etc.',
      name: 'Jjapke-Mon',
      link: '',
      screenshot: [],
      discription: '',
      stackTags: ['C++', 'Console Application', 'Game'],
      content: '',
    },
    {
      id: 14,
      category: 'Etc.',
      name: 'Jjaplu-Marble',
      link: '',
      screenshot: [],
      discription: '',
      stackTags: ['JAVA', 'GUI Application', 'Swing', 'AWT', 'Game'],
      content: '',
    },
    {
      id: 15,
      category: 'Etc.',
      name: 'OSS-MineSweeper',
      link: '',
      screenshot: [],
      discription: '',
      stackTags: ['C', 'Console Application', 'Git', 'TeamWork', 'Cleancode', 'Refactoring'],
      content: '',
    },
  ],
};
